 name: Orthanc Plugins Docker Image Build and Push
 on:
   workflow_dispatch:
 jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
           ref: 1.12.0
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
         with:
           platforms: 'arm64,arm'
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       - name: Login to DockerHub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USER }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
       - name: Build and push
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./orthanc-plugins/Dockerfile
           platforms: linux/arm64
           push: true
           tags: jonah1024/orthanc-plugins:1.12.0